### ISSUE TITLE
Simplify table making

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/snakemake-econ-r#1]
Currently have six rules in `rules/tables.smk`

Move towards one rule that accepts a json file (i.e. table_1.json) and runs it thru a R Script ('make_table.R').

then we can have a wildcard  + expand to loop thru each .json file

**Comment by bergmul** [comment]
I added a tentative .json file for the first table. It's in the `features/unify-table` branch under commit `e8b90135dc959d23137704dd88aa6e8ee755fa71`.

Please have a look if I missed any variables which might vary between tables.

**Comment by bergmul** [comment]
Alternatively one could just pass the full stargazer command in a single json or R file as a lazy solution :)
